=== Wetator/wetator_history/test/xml/testcase.dtd
<!ELEMENT testcase (step+)>
<!ELEMENT step (parameter, optionalParameter?)>
<!ELEMENT parameter (#PCDATA)>
<!ELEMENT optionalParameter (#PCDATA)>

<!ATTLIST step
    command (Assert_Content | Assert_Title | Click_After_Text | Click_On | Comment | Open_Url | Select | Set | Use_Module) #REQUIRED
    comment (true | false) "false">

=== Wetator/wetator_history/test/xml/ajax_prototype.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "testcase.dtd"><testcase><step command="Aktion" comment="true"><![CDATA[Parameter]]><optionalParameter><![CDATA[opt. Parameter]]></optionalParameter></step><step command="Open_Url"><![CDATA[ajax/prototype/prototype_ajax.html]]></step><step command="Assert_Title"><![CDATA[Wetator / AJAX with Prototype]]></step><step command="Comment"><![CDATA[add content via AJAX]]></step><step command="Comment"><![CDATA[check the original content]]></step><step command="Assert_Content"><![CDATA[Click to start AJAX demo...]]></step><step command="Click_On"><![CDATA[Click to start AJAX demo]]></step><step command="Comment"></step><step command="Assert_Content"><![CDATA[This is some text transferred to the client via AJAX.]]></step><step command="Comment"></step><step command="Comment"></step><step command="Open_Url"><![CDATA[ajax/prototype/prototype_ajax.html]]></step><step command="Assert_Title"><![CDATA[Wetator / AJAX with Prototype]]></step><step command="Comment"><![CDATA[change content via javascript loaded with AJAX]]></step><step command="Comment"><![CDATA[check the original content]]></step><step command="Assert_Content"><![CDATA[Click to start AJAX Javascript demo...]]></step><step command="Click_On"><![CDATA[Click to start AJAX Javascript demo]]></step><step command="Comment"></step><step command="Assert_Content"><![CDATA[Click to start AJAX Javascript demo... Javascript Execute]]></step></testcase>

=== Wetator/wetator_history/test/xml/jquery/modal_confirmation.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "testcase.dtd"><testcase><step command="Aktion" comment="true"><![CDATA[Parameter]]><optionalParameter><![CDATA[opt. Parameter]]></optionalParameter></step><step command="Open_Url"><![CDATA[js/jquery/modal-confirmation.html]]></step><step command="Assert_Content"><![CDATA[Empty the recycle bin?]]></step><step command="Click_On"><![CDATA[Cancel]]></step><step command="Assert_Content"><![CDATA[Button: Cancel]]></step><step command="Comment"></step><step command="Open_Url"><![CDATA[js/jquery/modal-confirmation.html]]></step><step command="Assert_Content"><![CDATA[Empty the recycle bin?]]></step><step command="Click_On"><![CDATA[Delete all items]]></step><step command="Assert_Content"><![CDATA[Button: Delete all items]]></step></testcase>

=== Wetator/wetator_history/test/xml/use_module.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "testcase.dtd"><testcase><step command="Aktion" comment="true"><![CDATA[Parameter]]><optionalParameter><![CDATA[opt. Parameter]]></optionalParameter></step><step command="Open_Url"><![CDATA[testcases.html]]></step><step command="Use_Module"><![CDATA[modules/module.xml]]></step><step command="Comment"><![CDATA[after use module]]></step><step command="Comment"></step><step command="Comment"><![CDATA[module with parameter]]></step><step command="Use_Module"><![CDATA[modules/module_with_parameters.xml]]><optionalParameter><![CDATA[assert_content.html, Wetator / Assert Content]]></optionalParameter></step></testcase>

=== Wetator/wetator_history/test/xml/wait.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE testcase SYSTEM "testcase.dtd"><testcase><step command="Aktion" comment="true"><![CDATA[Parameter]]><optionalParameter><![CDATA[opt. Parameter]]></optionalParameter></step><step command="Open_Url"><![CDATA[wait_for.html]]></step><step command="Assert_Title"><![CDATA[Wetator / Wait For]]></step><step command="Comment"><![CDATA[click the link]]></step><step command="Click_On"><![CDATA[startIndirectJump]]></step><step command="Assert_Content"><![CDATA[Wait For Result page]]></step></testcase>
